apiVersion: apps/v1
kind: Deployment
metadata:
  name: shardora-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shardora
  template:
    metadata:
      labels:
        app: shardora
    spec:
      containers:
      - name: shardora-container
        image: shardora_docker:latest
        command: ["/bin/sh"]
        args: ["-c", "sh docker_simple_dep.sh 4 Debug && sleep infinity"]
        imagePullPolicy: Never
        ports:
        - containerPort: 23001

