[db]
path = "./db"

[log]
path = "log/shardora.log"

[shardora]
bootstrap = BOOTSTRAP
bootstrap_net =
consensus_thread_count = 16
each_shard_max_members = 1024
sharding_min_nodes_count = 2
join_root = 1
country = "NL"
first_node = 0
http_port = HTTP_PORT
local_ip = LOCAL_IP
local_port = LOCAL_PORT
public_ip = PUBLIC_IP
public_port = LOCAL_PORT
net_id = 3
node_tag =
prikey = PRIVATE_KEY
show_cmd = 0
for_ck = FOR_CK_CLIENT
root_path = .
server_cert_path = ./server-cert.pem
server_key_path = ./server-key.pem
missing_node = 0
ck_host = 127.0.0.1
ck_port = 9000
ck_user = default
ck_pass =
ip_db_path = ./conf/GeoLite2-City.mmdb
tx_user_qps_limit_window = 102400
tx_user_qps_limit_window_sconds = 1
each_tx_pool_max_txs = 40960
test_pool_index = TEST_POOL_INDEX
test_tx_tps = TEST_TX_TPS
leader_change_init_tm = LEADER_CHANGE_INIT_TM
tx_ws_ip = 0.0.0.0
tx_ws_port = TX_WS_PORT

[tx_block]
network_id = 3
