// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/init.proto

#ifndef PROTOBUF_INCLUDED_protos_2finit_2eproto
#define PROTOBUF_INCLUDED_protos_2finit_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "protos/bls.pb.h"
#include "protos/block.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_protos_2finit_2eproto 

namespace protobuf_protos_2finit_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_protos_2finit_2eproto
namespace zjchain {
namespace init {
namespace protobuf {
class GenesisInitBlsInfo;
class GenesisInitBlsInfoDefaultTypeInternal;
extern GenesisInitBlsInfoDefaultTypeInternal _GenesisInitBlsInfo_default_instance_;
class GetAddressInfoRequest;
class GetAddressInfoRequestDefaultTypeInternal;
extern GetAddressInfoRequestDefaultTypeInternal _GetAddressInfoRequest_default_instance_;
class GetAddressInfoResponse;
class GetAddressInfoResponseDefaultTypeInternal;
extern GetAddressInfoResponseDefaultTypeInternal _GetAddressInfoResponse_default_instance_;
class InitMessage;
class InitMessageDefaultTypeInternal;
extern InitMessageDefaultTypeInternal _InitMessage_default_instance_;
class InvalidLeaderPools;
class InvalidLeaderPoolsDefaultTypeInternal;
extern InvalidLeaderPoolsDefaultTypeInternal _InvalidLeaderPools_default_instance_;
}  // namespace protobuf
}  // namespace init
}  // namespace zjchain
namespace google {
namespace protobuf {
template<> ::zjchain::init::protobuf::GenesisInitBlsInfo* Arena::CreateMaybeMessage<::zjchain::init::protobuf::GenesisInitBlsInfo>(Arena*);
template<> ::zjchain::init::protobuf::GetAddressInfoRequest* Arena::CreateMaybeMessage<::zjchain::init::protobuf::GetAddressInfoRequest>(Arena*);
template<> ::zjchain::init::protobuf::GetAddressInfoResponse* Arena::CreateMaybeMessage<::zjchain::init::protobuf::GetAddressInfoResponse>(Arena*);
template<> ::zjchain::init::protobuf::InitMessage* Arena::CreateMaybeMessage<::zjchain::init::protobuf::InitMessage>(Arena*);
template<> ::zjchain::init::protobuf::InvalidLeaderPools* Arena::CreateMaybeMessage<::zjchain::init::protobuf::InvalidLeaderPools>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zjchain {
namespace init {
namespace protobuf {

// ===================================================================

class GetAddressInfoRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjchain.init.protobuf.GetAddressInfoRequest) */ {
 public:
  GetAddressInfoRequest();
  virtual ~GetAddressInfoRequest();

  GetAddressInfoRequest(const GetAddressInfoRequest& from);

  inline GetAddressInfoRequest& operator=(const GetAddressInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetAddressInfoRequest(GetAddressInfoRequest&& from) noexcept
    : GetAddressInfoRequest() {
    *this = ::std::move(from);
  }

  inline GetAddressInfoRequest& operator=(GetAddressInfoRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetAddressInfoRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetAddressInfoRequest* internal_default_instance() {
    return reinterpret_cast<const GetAddressInfoRequest*>(
               &_GetAddressInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GetAddressInfoRequest* other);
  friend void swap(GetAddressInfoRequest& a, GetAddressInfoRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetAddressInfoRequest* New() const final {
    return CreateMaybeMessage<GetAddressInfoRequest>(NULL);
  }

  GetAddressInfoRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetAddressInfoRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetAddressInfoRequest& from);
  void MergeFrom(const GetAddressInfoRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAddressInfoRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:zjchain.init.protobuf.GetAddressInfoRequest)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  friend struct ::protobuf_protos_2finit_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetAddressInfoResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjchain.init.protobuf.GetAddressInfoResponse) */ {
 public:
  GetAddressInfoResponse();
  virtual ~GetAddressInfoResponse();

  GetAddressInfoResponse(const GetAddressInfoResponse& from);

  inline GetAddressInfoResponse& operator=(const GetAddressInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetAddressInfoResponse(GetAddressInfoResponse&& from) noexcept
    : GetAddressInfoResponse() {
    *this = ::std::move(from);
  }

  inline GetAddressInfoResponse& operator=(GetAddressInfoResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetAddressInfoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetAddressInfoResponse* internal_default_instance() {
    return reinterpret_cast<const GetAddressInfoResponse*>(
               &_GetAddressInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GetAddressInfoResponse* other);
  friend void swap(GetAddressInfoResponse& a, GetAddressInfoResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetAddressInfoResponse* New() const final {
    return CreateMaybeMessage<GetAddressInfoResponse>(NULL);
  }

  GetAddressInfoResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetAddressInfoResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetAddressInfoResponse& from);
  void MergeFrom(const GetAddressInfoResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAddressInfoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .zjchain.block.protobuf.Block block = 1;
  bool has_block() const;
  void clear_block();
  static const int kBlockFieldNumber = 1;
  private:
  const ::zjchain::block::protobuf::Block& _internal_block() const;
  public:
  const ::zjchain::block::protobuf::Block& block() const;
  ::zjchain::block::protobuf::Block* release_block();
  ::zjchain::block::protobuf::Block* mutable_block();
  void set_allocated_block(::zjchain::block::protobuf::Block* block);

  // @@protoc_insertion_point(class_scope:zjchain.init.protobuf.GetAddressInfoResponse)
 private:
  void set_has_block();
  void clear_has_block();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::zjchain::block::protobuf::Block* block_;
  friend struct ::protobuf_protos_2finit_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InvalidLeaderPools : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjchain.init.protobuf.InvalidLeaderPools) */ {
 public:
  InvalidLeaderPools();
  virtual ~InvalidLeaderPools();

  InvalidLeaderPools(const InvalidLeaderPools& from);

  inline InvalidLeaderPools& operator=(const InvalidLeaderPools& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InvalidLeaderPools(InvalidLeaderPools&& from) noexcept
    : InvalidLeaderPools() {
    *this = ::std::move(from);
  }

  inline InvalidLeaderPools& operator=(InvalidLeaderPools&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InvalidLeaderPools& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InvalidLeaderPools* internal_default_instance() {
    return reinterpret_cast<const InvalidLeaderPools*>(
               &_InvalidLeaderPools_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(InvalidLeaderPools* other);
  friend void swap(InvalidLeaderPools& a, InvalidLeaderPools& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InvalidLeaderPools* New() const final {
    return CreateMaybeMessage<InvalidLeaderPools>(NULL);
  }

  InvalidLeaderPools* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InvalidLeaderPools>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InvalidLeaderPools& from);
  void MergeFrom(const InvalidLeaderPools& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InvalidLeaderPools* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 pools = 1;
  int pools_size() const;
  void clear_pools();
  static const int kPoolsFieldNumber = 1;
  ::google::protobuf::int32 pools(int index) const;
  void set_pools(int index, ::google::protobuf::int32 value);
  void add_pools(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      pools() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_pools();

  // optional uint64 elect_height = 2;
  bool has_elect_height() const;
  void clear_elect_height();
  static const int kElectHeightFieldNumber = 2;
  ::google::protobuf::uint64 elect_height() const;
  void set_elect_height(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:zjchain.init.protobuf.InvalidLeaderPools)
 private:
  void set_has_elect_height();
  void clear_has_elect_height();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > pools_;
  ::google::protobuf::uint64 elect_height_;
  friend struct ::protobuf_protos_2finit_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GenesisInitBlsInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjchain.init.protobuf.GenesisInitBlsInfo) */ {
 public:
  GenesisInitBlsInfo();
  virtual ~GenesisInitBlsInfo();

  GenesisInitBlsInfo(const GenesisInitBlsInfo& from);

  inline GenesisInitBlsInfo& operator=(const GenesisInitBlsInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenesisInitBlsInfo(GenesisInitBlsInfo&& from) noexcept
    : GenesisInitBlsInfo() {
    *this = ::std::move(from);
  }

  inline GenesisInitBlsInfo& operator=(GenesisInitBlsInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GenesisInitBlsInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenesisInitBlsInfo* internal_default_instance() {
    return reinterpret_cast<const GenesisInitBlsInfo*>(
               &_GenesisInitBlsInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GenesisInitBlsInfo* other);
  friend void swap(GenesisInitBlsInfo& a, GenesisInitBlsInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenesisInitBlsInfo* New() const final {
    return CreateMaybeMessage<GenesisInitBlsInfo>(NULL);
  }

  GenesisInitBlsInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GenesisInitBlsInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GenesisInitBlsInfo& from);
  void MergeFrom(const GenesisInitBlsInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenesisInitBlsInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes id = 3;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 3;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const void* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional bytes bls_enc_data = 4;
  bool has_bls_enc_data() const;
  void clear_bls_enc_data();
  static const int kBlsEncDataFieldNumber = 4;
  const ::std::string& bls_enc_data() const;
  void set_bls_enc_data(const ::std::string& value);
  #if LANG_CXX11
  void set_bls_enc_data(::std::string&& value);
  #endif
  void set_bls_enc_data(const char* value);
  void set_bls_enc_data(const void* value, size_t size);
  ::std::string* mutable_bls_enc_data();
  ::std::string* release_bls_enc_data();
  void set_allocated_bls_enc_data(::std::string* bls_enc_data);

  // optional bytes bls_hash = 5;
  bool has_bls_hash() const;
  void clear_bls_hash();
  static const int kBlsHashFieldNumber = 5;
  const ::std::string& bls_hash() const;
  void set_bls_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_bls_hash(::std::string&& value);
  #endif
  void set_bls_hash(const char* value);
  void set_bls_hash(const void* value, size_t size);
  ::std::string* mutable_bls_hash();
  ::std::string* release_bls_hash();
  void set_allocated_bls_hash(::std::string* bls_hash);

  // optional bytes prikey = 8;
  bool has_prikey() const;
  void clear_prikey();
  static const int kPrikeyFieldNumber = 8;
  const ::std::string& prikey() const;
  void set_prikey(const ::std::string& value);
  #if LANG_CXX11
  void set_prikey(::std::string&& value);
  #endif
  void set_prikey(const char* value);
  void set_prikey(const void* value, size_t size);
  ::std::string* mutable_prikey();
  ::std::string* release_prikey();
  void set_allocated_prikey(::std::string* prikey);

  // optional .zjchain.bls.protobuf.JoinElectInfo join_info = 6;
  bool has_join_info() const;
  void clear_join_info();
  static const int kJoinInfoFieldNumber = 6;
  private:
  const ::zjchain::bls::protobuf::JoinElectInfo& _internal_join_info() const;
  public:
  const ::zjchain::bls::protobuf::JoinElectInfo& join_info() const;
  ::zjchain::bls::protobuf::JoinElectInfo* release_join_info();
  ::zjchain::bls::protobuf::JoinElectInfo* mutable_join_info();
  void set_allocated_join_info(::zjchain::bls::protobuf::JoinElectInfo* join_info);

  // optional .zjchain.bls.protobuf.LocalPolynomial local_poly = 7;
  bool has_local_poly() const;
  void clear_local_poly();
  static const int kLocalPolyFieldNumber = 7;
  private:
  const ::zjchain::bls::protobuf::LocalPolynomial& _internal_local_poly() const;
  public:
  const ::zjchain::bls::protobuf::LocalPolynomial& local_poly() const;
  ::zjchain::bls::protobuf::LocalPolynomial* release_local_poly();
  ::zjchain::bls::protobuf::LocalPolynomial* mutable_local_poly();
  void set_allocated_local_poly(::zjchain::bls::protobuf::LocalPolynomial* local_poly);

  // optional uint64 height = 1;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 1;
  ::google::protobuf::uint64 height() const;
  void set_height(::google::protobuf::uint64 value);

  // optional uint32 shard_id = 2;
  bool has_shard_id() const;
  void clear_shard_id();
  static const int kShardIdFieldNumber = 2;
  ::google::protobuf::uint32 shard_id() const;
  void set_shard_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zjchain.init.protobuf.GenesisInitBlsInfo)
 private:
  void set_has_height();
  void clear_has_height();
  void set_has_shard_id();
  void clear_has_shard_id();
  void set_has_id();
  void clear_has_id();
  void set_has_bls_enc_data();
  void clear_has_bls_enc_data();
  void set_has_bls_hash();
  void clear_has_bls_hash();
  void set_has_join_info();
  void clear_has_join_info();
  void set_has_local_poly();
  void clear_has_local_poly();
  void set_has_prikey();
  void clear_has_prikey();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr bls_enc_data_;
  ::google::protobuf::internal::ArenaStringPtr bls_hash_;
  ::google::protobuf::internal::ArenaStringPtr prikey_;
  ::zjchain::bls::protobuf::JoinElectInfo* join_info_;
  ::zjchain::bls::protobuf::LocalPolynomial* local_poly_;
  ::google::protobuf::uint64 height_;
  ::google::protobuf::uint32 shard_id_;
  friend struct ::protobuf_protos_2finit_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InitMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zjchain.init.protobuf.InitMessage) */ {
 public:
  InitMessage();
  virtual ~InitMessage();

  InitMessage(const InitMessage& from);

  inline InitMessage& operator=(const InitMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InitMessage(InitMessage&& from) noexcept
    : InitMessage() {
    *this = ::std::move(from);
  }

  inline InitMessage& operator=(InitMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InitMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InitMessage* internal_default_instance() {
    return reinterpret_cast<const InitMessage*>(
               &_InitMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(InitMessage* other);
  friend void swap(InitMessage& a, InitMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InitMessage* New() const final {
    return CreateMaybeMessage<InitMessage>(NULL);
  }

  InitMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InitMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InitMessage& from);
  void MergeFrom(const InitMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InitMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .zjchain.init.protobuf.GetAddressInfoRequest addr_req = 1;
  bool has_addr_req() const;
  void clear_addr_req();
  static const int kAddrReqFieldNumber = 1;
  private:
  const ::zjchain::init::protobuf::GetAddressInfoRequest& _internal_addr_req() const;
  public:
  const ::zjchain::init::protobuf::GetAddressInfoRequest& addr_req() const;
  ::zjchain::init::protobuf::GetAddressInfoRequest* release_addr_req();
  ::zjchain::init::protobuf::GetAddressInfoRequest* mutable_addr_req();
  void set_allocated_addr_req(::zjchain::init::protobuf::GetAddressInfoRequest* addr_req);

  // optional .zjchain.init.protobuf.GetAddressInfoResponse addr_res = 2;
  bool has_addr_res() const;
  void clear_addr_res();
  static const int kAddrResFieldNumber = 2;
  private:
  const ::zjchain::init::protobuf::GetAddressInfoResponse& _internal_addr_res() const;
  public:
  const ::zjchain::init::protobuf::GetAddressInfoResponse& addr_res() const;
  ::zjchain::init::protobuf::GetAddressInfoResponse* release_addr_res();
  ::zjchain::init::protobuf::GetAddressInfoResponse* mutable_addr_res();
  void set_allocated_addr_res(::zjchain::init::protobuf::GetAddressInfoResponse* addr_res);

  // optional .zjchain.init.protobuf.InvalidLeaderPools pools = 3;
  bool has_pools() const;
  void clear_pools();
  static const int kPoolsFieldNumber = 3;
  private:
  const ::zjchain::init::protobuf::InvalidLeaderPools& _internal_pools() const;
  public:
  const ::zjchain::init::protobuf::InvalidLeaderPools& pools() const;
  ::zjchain::init::protobuf::InvalidLeaderPools* release_pools();
  ::zjchain::init::protobuf::InvalidLeaderPools* mutable_pools();
  void set_allocated_pools(::zjchain::init::protobuf::InvalidLeaderPools* pools);

  // @@protoc_insertion_point(class_scope:zjchain.init.protobuf.InitMessage)
 private:
  void set_has_addr_req();
  void clear_has_addr_req();
  void set_has_addr_res();
  void clear_has_addr_res();
  void set_has_pools();
  void clear_has_pools();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::zjchain::init::protobuf::GetAddressInfoRequest* addr_req_;
  ::zjchain::init::protobuf::GetAddressInfoResponse* addr_res_;
  ::zjchain::init::protobuf::InvalidLeaderPools* pools_;
  friend struct ::protobuf_protos_2finit_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetAddressInfoRequest

// optional bytes id = 1;
inline bool GetAddressInfoRequest::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetAddressInfoRequest::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetAddressInfoRequest::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetAddressInfoRequest::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& GetAddressInfoRequest::id() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GetAddressInfoRequest.id)
  return id_.GetNoArena();
}
inline void GetAddressInfoRequest::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GetAddressInfoRequest.id)
}
#if LANG_CXX11
inline void GetAddressInfoRequest::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zjchain.init.protobuf.GetAddressInfoRequest.id)
}
#endif
inline void GetAddressInfoRequest::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjchain.init.protobuf.GetAddressInfoRequest.id)
}
inline void GetAddressInfoRequest::set_id(const void* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjchain.init.protobuf.GetAddressInfoRequest.id)
}
inline ::std::string* GetAddressInfoRequest::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GetAddressInfoRequest.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetAddressInfoRequest::release_id() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GetAddressInfoRequest.id)
  if (!has_id()) {
    return NULL;
  }
  clear_has_id();
  return id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetAddressInfoRequest::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GetAddressInfoRequest.id)
}

// -------------------------------------------------------------------

// GetAddressInfoResponse

// optional .zjchain.block.protobuf.Block block = 1;
inline bool GetAddressInfoResponse::has_block() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetAddressInfoResponse::set_has_block() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetAddressInfoResponse::clear_has_block() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::zjchain::block::protobuf::Block& GetAddressInfoResponse::_internal_block() const {
  return *block_;
}
inline const ::zjchain::block::protobuf::Block& GetAddressInfoResponse::block() const {
  const ::zjchain::block::protobuf::Block* p = block_;
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GetAddressInfoResponse.block)
  return p != NULL ? *p : *reinterpret_cast<const ::zjchain::block::protobuf::Block*>(
      &::zjchain::block::protobuf::_Block_default_instance_);
}
inline ::zjchain::block::protobuf::Block* GetAddressInfoResponse::release_block() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GetAddressInfoResponse.block)
  clear_has_block();
  ::zjchain::block::protobuf::Block* temp = block_;
  block_ = NULL;
  return temp;
}
inline ::zjchain::block::protobuf::Block* GetAddressInfoResponse::mutable_block() {
  set_has_block();
  if (block_ == NULL) {
    auto* p = CreateMaybeMessage<::zjchain::block::protobuf::Block>(GetArenaNoVirtual());
    block_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GetAddressInfoResponse.block)
  return block_;
}
inline void GetAddressInfoResponse::set_allocated_block(::zjchain::block::protobuf::Block* block) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(block_);
  }
  if (block) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      block = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, block, submessage_arena);
    }
    set_has_block();
  } else {
    clear_has_block();
  }
  block_ = block;
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GetAddressInfoResponse.block)
}

// -------------------------------------------------------------------

// InvalidLeaderPools

// repeated int32 pools = 1;
inline int InvalidLeaderPools::pools_size() const {
  return pools_.size();
}
inline void InvalidLeaderPools::clear_pools() {
  pools_.Clear();
}
inline ::google::protobuf::int32 InvalidLeaderPools::pools(int index) const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.InvalidLeaderPools.pools)
  return pools_.Get(index);
}
inline void InvalidLeaderPools::set_pools(int index, ::google::protobuf::int32 value) {
  pools_.Set(index, value);
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.InvalidLeaderPools.pools)
}
inline void InvalidLeaderPools::add_pools(::google::protobuf::int32 value) {
  pools_.Add(value);
  // @@protoc_insertion_point(field_add:zjchain.init.protobuf.InvalidLeaderPools.pools)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
InvalidLeaderPools::pools() const {
  // @@protoc_insertion_point(field_list:zjchain.init.protobuf.InvalidLeaderPools.pools)
  return pools_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
InvalidLeaderPools::mutable_pools() {
  // @@protoc_insertion_point(field_mutable_list:zjchain.init.protobuf.InvalidLeaderPools.pools)
  return &pools_;
}

// optional uint64 elect_height = 2;
inline bool InvalidLeaderPools::has_elect_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InvalidLeaderPools::set_has_elect_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InvalidLeaderPools::clear_has_elect_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InvalidLeaderPools::clear_elect_height() {
  elect_height_ = GOOGLE_ULONGLONG(0);
  clear_has_elect_height();
}
inline ::google::protobuf::uint64 InvalidLeaderPools::elect_height() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.InvalidLeaderPools.elect_height)
  return elect_height_;
}
inline void InvalidLeaderPools::set_elect_height(::google::protobuf::uint64 value) {
  set_has_elect_height();
  elect_height_ = value;
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.InvalidLeaderPools.elect_height)
}

// -------------------------------------------------------------------

// GenesisInitBlsInfo

// optional uint64 height = 1;
inline bool GenesisInitBlsInfo::has_height() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GenesisInitBlsInfo::set_has_height() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GenesisInitBlsInfo::clear_has_height() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GenesisInitBlsInfo::clear_height() {
  height_ = GOOGLE_ULONGLONG(0);
  clear_has_height();
}
inline ::google::protobuf::uint64 GenesisInitBlsInfo::height() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.height)
  return height_;
}
inline void GenesisInitBlsInfo::set_height(::google::protobuf::uint64 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GenesisInitBlsInfo.height)
}

// optional uint32 shard_id = 2;
inline bool GenesisInitBlsInfo::has_shard_id() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void GenesisInitBlsInfo::set_has_shard_id() {
  _has_bits_[0] |= 0x00000080u;
}
inline void GenesisInitBlsInfo::clear_has_shard_id() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void GenesisInitBlsInfo::clear_shard_id() {
  shard_id_ = 0u;
  clear_has_shard_id();
}
inline ::google::protobuf::uint32 GenesisInitBlsInfo::shard_id() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.shard_id)
  return shard_id_;
}
inline void GenesisInitBlsInfo::set_shard_id(::google::protobuf::uint32 value) {
  set_has_shard_id();
  shard_id_ = value;
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GenesisInitBlsInfo.shard_id)
}

// optional bytes id = 3;
inline bool GenesisInitBlsInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GenesisInitBlsInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GenesisInitBlsInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GenesisInitBlsInfo::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& GenesisInitBlsInfo::id() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.id)
  return id_.GetNoArena();
}
inline void GenesisInitBlsInfo::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GenesisInitBlsInfo.id)
}
#if LANG_CXX11
inline void GenesisInitBlsInfo::set_id(::std::string&& value) {
  set_has_id();
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zjchain.init.protobuf.GenesisInitBlsInfo.id)
}
#endif
inline void GenesisInitBlsInfo::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjchain.init.protobuf.GenesisInitBlsInfo.id)
}
inline void GenesisInitBlsInfo::set_id(const void* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjchain.init.protobuf.GenesisInitBlsInfo.id)
}
inline ::std::string* GenesisInitBlsInfo::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GenesisInitBlsInfo.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenesisInitBlsInfo::release_id() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GenesisInitBlsInfo.id)
  if (!has_id()) {
    return NULL;
  }
  clear_has_id();
  return id_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenesisInitBlsInfo::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GenesisInitBlsInfo.id)
}

// optional bytes bls_enc_data = 4;
inline bool GenesisInitBlsInfo::has_bls_enc_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GenesisInitBlsInfo::set_has_bls_enc_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GenesisInitBlsInfo::clear_has_bls_enc_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GenesisInitBlsInfo::clear_bls_enc_data() {
  bls_enc_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_bls_enc_data();
}
inline const ::std::string& GenesisInitBlsInfo::bls_enc_data() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
  return bls_enc_data_.GetNoArena();
}
inline void GenesisInitBlsInfo::set_bls_enc_data(const ::std::string& value) {
  set_has_bls_enc_data();
  bls_enc_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
}
#if LANG_CXX11
inline void GenesisInitBlsInfo::set_bls_enc_data(::std::string&& value) {
  set_has_bls_enc_data();
  bls_enc_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
}
#endif
inline void GenesisInitBlsInfo::set_bls_enc_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_bls_enc_data();
  bls_enc_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
}
inline void GenesisInitBlsInfo::set_bls_enc_data(const void* value, size_t size) {
  set_has_bls_enc_data();
  bls_enc_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
}
inline ::std::string* GenesisInitBlsInfo::mutable_bls_enc_data() {
  set_has_bls_enc_data();
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
  return bls_enc_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenesisInitBlsInfo::release_bls_enc_data() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
  if (!has_bls_enc_data()) {
    return NULL;
  }
  clear_has_bls_enc_data();
  return bls_enc_data_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenesisInitBlsInfo::set_allocated_bls_enc_data(::std::string* bls_enc_data) {
  if (bls_enc_data != NULL) {
    set_has_bls_enc_data();
  } else {
    clear_has_bls_enc_data();
  }
  bls_enc_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bls_enc_data);
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GenesisInitBlsInfo.bls_enc_data)
}

// optional bytes bls_hash = 5;
inline bool GenesisInitBlsInfo::has_bls_hash() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GenesisInitBlsInfo::set_has_bls_hash() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GenesisInitBlsInfo::clear_has_bls_hash() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GenesisInitBlsInfo::clear_bls_hash() {
  bls_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_bls_hash();
}
inline const ::std::string& GenesisInitBlsInfo::bls_hash() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
  return bls_hash_.GetNoArena();
}
inline void GenesisInitBlsInfo::set_bls_hash(const ::std::string& value) {
  set_has_bls_hash();
  bls_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
}
#if LANG_CXX11
inline void GenesisInitBlsInfo::set_bls_hash(::std::string&& value) {
  set_has_bls_hash();
  bls_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
}
#endif
inline void GenesisInitBlsInfo::set_bls_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_bls_hash();
  bls_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
}
inline void GenesisInitBlsInfo::set_bls_hash(const void* value, size_t size) {
  set_has_bls_hash();
  bls_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
}
inline ::std::string* GenesisInitBlsInfo::mutable_bls_hash() {
  set_has_bls_hash();
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
  return bls_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenesisInitBlsInfo::release_bls_hash() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
  if (!has_bls_hash()) {
    return NULL;
  }
  clear_has_bls_hash();
  return bls_hash_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenesisInitBlsInfo::set_allocated_bls_hash(::std::string* bls_hash) {
  if (bls_hash != NULL) {
    set_has_bls_hash();
  } else {
    clear_has_bls_hash();
  }
  bls_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bls_hash);
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GenesisInitBlsInfo.bls_hash)
}

// optional .zjchain.bls.protobuf.JoinElectInfo join_info = 6;
inline bool GenesisInitBlsInfo::has_join_info() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GenesisInitBlsInfo::set_has_join_info() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GenesisInitBlsInfo::clear_has_join_info() {
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::zjchain::bls::protobuf::JoinElectInfo& GenesisInitBlsInfo::_internal_join_info() const {
  return *join_info_;
}
inline const ::zjchain::bls::protobuf::JoinElectInfo& GenesisInitBlsInfo::join_info() const {
  const ::zjchain::bls::protobuf::JoinElectInfo* p = join_info_;
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.join_info)
  return p != NULL ? *p : *reinterpret_cast<const ::zjchain::bls::protobuf::JoinElectInfo*>(
      &::zjchain::bls::protobuf::_JoinElectInfo_default_instance_);
}
inline ::zjchain::bls::protobuf::JoinElectInfo* GenesisInitBlsInfo::release_join_info() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GenesisInitBlsInfo.join_info)
  clear_has_join_info();
  ::zjchain::bls::protobuf::JoinElectInfo* temp = join_info_;
  join_info_ = NULL;
  return temp;
}
inline ::zjchain::bls::protobuf::JoinElectInfo* GenesisInitBlsInfo::mutable_join_info() {
  set_has_join_info();
  if (join_info_ == NULL) {
    auto* p = CreateMaybeMessage<::zjchain::bls::protobuf::JoinElectInfo>(GetArenaNoVirtual());
    join_info_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GenesisInitBlsInfo.join_info)
  return join_info_;
}
inline void GenesisInitBlsInfo::set_allocated_join_info(::zjchain::bls::protobuf::JoinElectInfo* join_info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(join_info_);
  }
  if (join_info) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      join_info = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, join_info, submessage_arena);
    }
    set_has_join_info();
  } else {
    clear_has_join_info();
  }
  join_info_ = join_info;
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GenesisInitBlsInfo.join_info)
}

// optional .zjchain.bls.protobuf.LocalPolynomial local_poly = 7;
inline bool GenesisInitBlsInfo::has_local_poly() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GenesisInitBlsInfo::set_has_local_poly() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GenesisInitBlsInfo::clear_has_local_poly() {
  _has_bits_[0] &= ~0x00000020u;
}
inline const ::zjchain::bls::protobuf::LocalPolynomial& GenesisInitBlsInfo::_internal_local_poly() const {
  return *local_poly_;
}
inline const ::zjchain::bls::protobuf::LocalPolynomial& GenesisInitBlsInfo::local_poly() const {
  const ::zjchain::bls::protobuf::LocalPolynomial* p = local_poly_;
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.local_poly)
  return p != NULL ? *p : *reinterpret_cast<const ::zjchain::bls::protobuf::LocalPolynomial*>(
      &::zjchain::bls::protobuf::_LocalPolynomial_default_instance_);
}
inline ::zjchain::bls::protobuf::LocalPolynomial* GenesisInitBlsInfo::release_local_poly() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GenesisInitBlsInfo.local_poly)
  clear_has_local_poly();
  ::zjchain::bls::protobuf::LocalPolynomial* temp = local_poly_;
  local_poly_ = NULL;
  return temp;
}
inline ::zjchain::bls::protobuf::LocalPolynomial* GenesisInitBlsInfo::mutable_local_poly() {
  set_has_local_poly();
  if (local_poly_ == NULL) {
    auto* p = CreateMaybeMessage<::zjchain::bls::protobuf::LocalPolynomial>(GetArenaNoVirtual());
    local_poly_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GenesisInitBlsInfo.local_poly)
  return local_poly_;
}
inline void GenesisInitBlsInfo::set_allocated_local_poly(::zjchain::bls::protobuf::LocalPolynomial* local_poly) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(local_poly_);
  }
  if (local_poly) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      local_poly = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, local_poly, submessage_arena);
    }
    set_has_local_poly();
  } else {
    clear_has_local_poly();
  }
  local_poly_ = local_poly;
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GenesisInitBlsInfo.local_poly)
}

// optional bytes prikey = 8;
inline bool GenesisInitBlsInfo::has_prikey() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GenesisInitBlsInfo::set_has_prikey() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GenesisInitBlsInfo::clear_has_prikey() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GenesisInitBlsInfo::clear_prikey() {
  prikey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_prikey();
}
inline const ::std::string& GenesisInitBlsInfo::prikey() const {
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
  return prikey_.GetNoArena();
}
inline void GenesisInitBlsInfo::set_prikey(const ::std::string& value) {
  set_has_prikey();
  prikey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
}
#if LANG_CXX11
inline void GenesisInitBlsInfo::set_prikey(::std::string&& value) {
  set_has_prikey();
  prikey_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
}
#endif
inline void GenesisInitBlsInfo::set_prikey(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_prikey();
  prikey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
}
inline void GenesisInitBlsInfo::set_prikey(const void* value, size_t size) {
  set_has_prikey();
  prikey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
}
inline ::std::string* GenesisInitBlsInfo::mutable_prikey() {
  set_has_prikey();
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
  return prikey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenesisInitBlsInfo::release_prikey() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
  if (!has_prikey()) {
    return NULL;
  }
  clear_has_prikey();
  return prikey_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenesisInitBlsInfo::set_allocated_prikey(::std::string* prikey) {
  if (prikey != NULL) {
    set_has_prikey();
  } else {
    clear_has_prikey();
  }
  prikey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), prikey);
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.GenesisInitBlsInfo.prikey)
}

// -------------------------------------------------------------------

// InitMessage

// optional .zjchain.init.protobuf.GetAddressInfoRequest addr_req = 1;
inline bool InitMessage::has_addr_req() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InitMessage::set_has_addr_req() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InitMessage::clear_has_addr_req() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InitMessage::clear_addr_req() {
  if (addr_req_ != NULL) addr_req_->Clear();
  clear_has_addr_req();
}
inline const ::zjchain::init::protobuf::GetAddressInfoRequest& InitMessage::_internal_addr_req() const {
  return *addr_req_;
}
inline const ::zjchain::init::protobuf::GetAddressInfoRequest& InitMessage::addr_req() const {
  const ::zjchain::init::protobuf::GetAddressInfoRequest* p = addr_req_;
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.InitMessage.addr_req)
  return p != NULL ? *p : *reinterpret_cast<const ::zjchain::init::protobuf::GetAddressInfoRequest*>(
      &::zjchain::init::protobuf::_GetAddressInfoRequest_default_instance_);
}
inline ::zjchain::init::protobuf::GetAddressInfoRequest* InitMessage::release_addr_req() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.InitMessage.addr_req)
  clear_has_addr_req();
  ::zjchain::init::protobuf::GetAddressInfoRequest* temp = addr_req_;
  addr_req_ = NULL;
  return temp;
}
inline ::zjchain::init::protobuf::GetAddressInfoRequest* InitMessage::mutable_addr_req() {
  set_has_addr_req();
  if (addr_req_ == NULL) {
    auto* p = CreateMaybeMessage<::zjchain::init::protobuf::GetAddressInfoRequest>(GetArenaNoVirtual());
    addr_req_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.InitMessage.addr_req)
  return addr_req_;
}
inline void InitMessage::set_allocated_addr_req(::zjchain::init::protobuf::GetAddressInfoRequest* addr_req) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete addr_req_;
  }
  if (addr_req) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      addr_req = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, addr_req, submessage_arena);
    }
    set_has_addr_req();
  } else {
    clear_has_addr_req();
  }
  addr_req_ = addr_req;
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.InitMessage.addr_req)
}

// optional .zjchain.init.protobuf.GetAddressInfoResponse addr_res = 2;
inline bool InitMessage::has_addr_res() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InitMessage::set_has_addr_res() {
  _has_bits_[0] |= 0x00000002u;
}
inline void InitMessage::clear_has_addr_res() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void InitMessage::clear_addr_res() {
  if (addr_res_ != NULL) addr_res_->Clear();
  clear_has_addr_res();
}
inline const ::zjchain::init::protobuf::GetAddressInfoResponse& InitMessage::_internal_addr_res() const {
  return *addr_res_;
}
inline const ::zjchain::init::protobuf::GetAddressInfoResponse& InitMessage::addr_res() const {
  const ::zjchain::init::protobuf::GetAddressInfoResponse* p = addr_res_;
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.InitMessage.addr_res)
  return p != NULL ? *p : *reinterpret_cast<const ::zjchain::init::protobuf::GetAddressInfoResponse*>(
      &::zjchain::init::protobuf::_GetAddressInfoResponse_default_instance_);
}
inline ::zjchain::init::protobuf::GetAddressInfoResponse* InitMessage::release_addr_res() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.InitMessage.addr_res)
  clear_has_addr_res();
  ::zjchain::init::protobuf::GetAddressInfoResponse* temp = addr_res_;
  addr_res_ = NULL;
  return temp;
}
inline ::zjchain::init::protobuf::GetAddressInfoResponse* InitMessage::mutable_addr_res() {
  set_has_addr_res();
  if (addr_res_ == NULL) {
    auto* p = CreateMaybeMessage<::zjchain::init::protobuf::GetAddressInfoResponse>(GetArenaNoVirtual());
    addr_res_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.InitMessage.addr_res)
  return addr_res_;
}
inline void InitMessage::set_allocated_addr_res(::zjchain::init::protobuf::GetAddressInfoResponse* addr_res) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete addr_res_;
  }
  if (addr_res) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      addr_res = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, addr_res, submessage_arena);
    }
    set_has_addr_res();
  } else {
    clear_has_addr_res();
  }
  addr_res_ = addr_res;
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.InitMessage.addr_res)
}

// optional .zjchain.init.protobuf.InvalidLeaderPools pools = 3;
inline bool InitMessage::has_pools() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void InitMessage::set_has_pools() {
  _has_bits_[0] |= 0x00000004u;
}
inline void InitMessage::clear_has_pools() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void InitMessage::clear_pools() {
  if (pools_ != NULL) pools_->Clear();
  clear_has_pools();
}
inline const ::zjchain::init::protobuf::InvalidLeaderPools& InitMessage::_internal_pools() const {
  return *pools_;
}
inline const ::zjchain::init::protobuf::InvalidLeaderPools& InitMessage::pools() const {
  const ::zjchain::init::protobuf::InvalidLeaderPools* p = pools_;
  // @@protoc_insertion_point(field_get:zjchain.init.protobuf.InitMessage.pools)
  return p != NULL ? *p : *reinterpret_cast<const ::zjchain::init::protobuf::InvalidLeaderPools*>(
      &::zjchain::init::protobuf::_InvalidLeaderPools_default_instance_);
}
inline ::zjchain::init::protobuf::InvalidLeaderPools* InitMessage::release_pools() {
  // @@protoc_insertion_point(field_release:zjchain.init.protobuf.InitMessage.pools)
  clear_has_pools();
  ::zjchain::init::protobuf::InvalidLeaderPools* temp = pools_;
  pools_ = NULL;
  return temp;
}
inline ::zjchain::init::protobuf::InvalidLeaderPools* InitMessage::mutable_pools() {
  set_has_pools();
  if (pools_ == NULL) {
    auto* p = CreateMaybeMessage<::zjchain::init::protobuf::InvalidLeaderPools>(GetArenaNoVirtual());
    pools_ = p;
  }
  // @@protoc_insertion_point(field_mutable:zjchain.init.protobuf.InitMessage.pools)
  return pools_;
}
inline void InitMessage::set_allocated_pools(::zjchain::init::protobuf::InvalidLeaderPools* pools) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete pools_;
  }
  if (pools) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pools = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pools, submessage_arena);
    }
    set_has_pools();
  } else {
    clear_has_pools();
  }
  pools_ = pools;
  // @@protoc_insertion_point(field_set_allocated:zjchain.init.protobuf.InitMessage.pools)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace init
}  // namespace zjchain

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_protos_2finit_2eproto
